server:
  port: 8290
  servlet:
    context-path: /map
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://114.55.64.105:3306/webtls_develop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: TXF19950605..
  jpa:
    show-sql: true